### PR TITLE
Cleanup composer reqs, use dev branch of behat extension

### PR DESCRIPTION
**Pull request by dnsl48**

### CODE REVIEW

**Comment by dnsl48** [comment]
@robbieaverill @maxime-rainville pls review. I don't have access to this repo.

**Review by maxime-rainville — APPROVED** [review]
Installed and confirmed Behat test still work.

Remove dependencies are already in the requirements for behat-extension.

**Comment by sminnee** [comment]
I've just picked this up – it's a bit weird to ban people from using stable's tags. It's a while ago but what was the motivation of this @dnsl48?

**Comment by sminnee** [comment]
Followed up with https://github.com/silverstripe/recipe-testing/pull/5/files

**Comment by dnsl48** [comment]
> I've just picked this up – it's a bit weird to ban people from using stable's tags. It's a while ago but what was the motivation of this @dnsl48?

If I remember correctly, that's been effort to make it follow the same conventions with other recipes. E.g. `recipe-core` branch `4` relies on `4.x-dev` branches of modules.
However, in this module that approach does not work, because we don't release it often and it's not a part of `silverstripe-installer`.

**Comment by sminnee** [comment]
Yeah this package doesn't have the release semantics of recipe-cms and recipe-core (modifying composer.json whenever the recipe is tagged), which are a bit too heavyweight for this package.

**Pull request merged**
